server:
  servlet:
    context-path: /api/v1
  max-http-header-size: 4194304
  tomcat:
    max-http-form-post-size: 4194304
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev, prod
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/atelier
  mail:
    host: smtp.gmail.com
    port: 587
    username: atelier.mail.server@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  custom:
    img:
      format: png
    security:
      permitted-matchers: >
        POST /users/**,
        GET /users/**,
        POST /authenticate,
        POST /patterns/calculate,
        GET /coat-models,
        GET /coat-models/**/images,
        GET /orders/**/metrics,
        GET /reviews/**,
        POST /clients/register/resend-email,
        GET /swagger-ui.html,
        GET /swagger-ui/**,
        GET /api-docs/**
    pagination:
      page-size: 5
  jwt:
    secret:
    expiration-time-millis: 604800000
logging:
  level:
    org:
      springframework:
        security: TRACE
springdoc:
  api-docs:
    path: /api-docs
---
spring:
  config:
    activate:
      on-profile: dev
  custom:
    frontend:
      domain: 'localhost:4200'
      protocol: http
---
spring:
  config:
    activate:
      on-profile: prod
  custom:
    frontend:
      domain: 'a-telie.web.app'
      protocol: https
server:
  ssl:
    key-store: classpath:keystore/atelier-keystore.p12
    key-store-password: atelier-admin



