server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atelier
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: atelier.mail.server@gmail.com
    password: rywh kjrd fruh pubs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
custom:
  frontend:
    domain: 'localhost:4200'
  security:
    permitted-matchers: >
      /users/activate/**
jwt:
  secret: KE73EYGWFWT378RTGFEW873R87F7TF8WYE7FT76FW6E76TF76ETFW76
  expiration-time-millis: 604800000
