server:
  servlet:
    context-path: /api/v1
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/atelier-key.p12
    key-store-password: atelier-admin
    key-alias: atelier
    enabled: true
  max-http-header-size: 4194304
  tomcat:
    max-http-form-post-size: 4194304
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev, prod
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/atelier
  mail:
    host: smtp.gmail.com
    port: 587
    username: atelier.mail.server@gmail.com
    password: rywh kjrd fruh pubs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  custom:
    security:
      permitted-matchers: >
        /users/activate/**,
        /authenticate,
        /patterns/calculate,
        /coat-models
  jwt:
    secret: KE73EYGWFWT378RTGFEW873R87F7TF8WYE7FT76FW6E76TF76ETFW76
    expiration-time-millis: 604800000
logging:
  level:
    org:
      springframework:
        security: TRACE
---
spring:
  config:
    activate:
      on-profile: dev
  custom:
    frontend:
      domain: 'localhost:4200'
---
spring:
  config:
    activate:
      on-profile: prod
  custom:
    frontend:
      domain: 'a-telier.web.app'



