server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atelier
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
